project:
  type: website
  output-dir: docs

website:
  title: "Chloe Rogozinski"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Resume-CV.qmd
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    mainfont: arial
    fontcolor: '#0b2239'
    linkcolor: '#142489'
    theme: sandstone
    css: styles.scss
    toc: true
    toc-location: right
    

editor: visual

